### ISSUE TITLE
A PATCH IN SPTCustomPlugin FAILED. SUBSEQUENT PATCHES HAVE NOT LOADED

### ISSUE THREAD

**Issue by DCCentR** [zhliau/fika-spt-server-docker#26]
Hi!

This error occurs when starting the game in the launcher (after connecting to the server):
![Image](https://github.com/user-attachments/assets/13d57892-c352-4e95-9dae-d4fa4dc997e3)

Log attached:
[LogOutput.log](https://github.com/user-attachments/files/20150131/LogOutput.log)

Container:
```
services:
  fika-server:
    image: ghcr.io/zhliau/fika-spt-server-docker:latest
    environment:
      # This will automatically set SPT server's configs to work in a containerized environment
      - LISTEN_ALL_NETWORKS=true
      - TZ=Europe/Moscow
      - TAKE_OWNERSHIP=false

    ports:
      - 6969:6969
    volumes:
      # Set this to an empty directory, or a directory containing your existing SPT server files
      - /Volume1/Data_1/docker/fika-spt-server:/opt/server
```

Container is running on my NAS, game client and SPT launcher is on my PC. What I do wrong?
